apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: bankapp-namespace
  labels:
    app: mysql
spec:
  clusterIP: None   # headless, required for StatefulSet # ClusterIP->none, pods are exposed individually via DNS StatefulSet requires stable DNS names per pod. Databases like MySQL, MongoDB, Kafka, Redis need to reach specific peers, not random ones.
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

