apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: bankapp-namespace
  labels:
    app: mysql
spec:
  clusterIP: None   # headless, required for StatefulSet
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

