apiVersion: v1
kind: PersistentVolume
metadata:
  name: bankapp-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  #If the PVC that is using this PV gets deleted, the PV and the data inside it will NOT be deleted.
  storageClassName: manual
  hostPath:
    path: /tmp/bankapp-mysql
